name: Build and Push Docker Image

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Harbor
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login harbor.main.rise-ck8s.com -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build Docker image
      run: |
        docker build -t harbor.main.rise-ck8s.com/des-public/tutorials:latest ./tutorials

    - name: Push Docker image
      run: docker push harbor.main.rise-ck8s.com/des-public/tutorials:latest

