name: Build and Publish Docker Image

on:
  push:
    branches:
      - '**'  # Trigger on push to any branch
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting main

concurrency:
  group: build-${{ github.ref }}  # Cancel in-progress builds from the same branch
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Max time to run before failure

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker registry
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login harbor.main.rise-ck8s.com -u "$DOCKER_USER" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t harbor.main.rise-ck8s.com/des-public/tutorials:latest .  # Build from root
          docker push harbor.main.rise-ck8s.com/des-public/tutorials:latest

      - name: Image digest
        run: echo ${{ steps.docker_meta.outputs.digest }}
