name: Build Docker Image

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    concurrency:
      group: build-${{ github.ref }}
      cancel-in-progress: true

    outputs:
      image_tag: ${{ steps.set_output.outputs.image_tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Generate image tag
        id: set_output
        run: echo "::set-output name=image_tag::${{ github.sha }}"  # Use Git SHA as unique tag

      - name: Build Docker image
        run: |
          docker build -t harbor.main.rise-ck8s.com/des-public/tutorials:${{ github.sha }} .

      - name: Upload Docker image
        run: |
          docker push harbor.main.rise-ck8s.com/des-public/tutorials:${{ github.sha }}
