name: Build Docker Image

on:
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  build_candidate:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker registry
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login harbor.main.rise-ck8s.com -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Print image tag
        run: |
          echo "Candidate Image Tag: ${{ github.sha }}"
       
          
      - name: Pull latest image as cache
        run: |
          docker pull harbor.main.rise-ck8s.com/des-public/tutorials:latest || true

      - name: Build Docker image using cache
        run: |
          docker buildx create --use
          docker buildx build \
            --platform linux/amd64,linux/arm64 \  # Specify multiple platforms
            --cache-from harbor.main.rise-ck8s.com/des-public/tutorials:latest \
            --tag harbor.main.rise-ck8s.com/des-public/tutorials:${{ github.sha }} \  # Tag with github.sha
            --push \
            .
      - name: Upload Docker image
        run: |
          docker push harbor.main.rise-ck8s.com/des-public/tutorials:${{ github.sha }}