name: Build and Publish Docker Image

on:
  push:
    branches:
      - main  # The branch to build on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Harbor
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login harbor.main.rise-ck8s.com -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t harbor.main.rise-ck8s.com/des-public/tutorials:latest ./tutorials
        docker push harbor.main.rise-ck8s.com/des-public/tutorials:latest

    - name: Image digest
      run: echo ${{ steps.docker_meta.outputs.digest }}

