# .github/workflows/docker-build.yml

name: Build and Publish Docker Image

on:
  push:
    branches:
      - main  # Change to the branch you want to build on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./tutorial  # Path to the folder containing the Dockerfile
        push: true
        tags: organization-name/tutorials:latest  # Replace with your organization's DockerHub name

    - name: Image digest
      run: echo ${{ steps.docker_meta.outputs.digest }}

