name: Publish Docker Image

on:
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:

      - name: Print image tag before test
        run: |
          echo "Image Tag: ${{ github.sha }}"

      - name: Log in to Docker registry
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login harbor.main.rise-ck8s.com -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag Docker image as "latest" and push
        run: |
          docker tag harbor.main.rise-ck8s.com/des-public/tutorials:${{ github.sha }} harbor.main.rise-ck8s.com/des-public/tutorials:latest
          docker push harbor.main.rise-ck8s.com/des-public/tutorials:latest
