name: Publish Docker Image

on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string  

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Docker registry
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login harbor.main.rise-ck8s.com -u "$DOCKER_USER" --password-stdin

      - name: Tag Docker image as "latest" and push
        run: |
          docker tag harbor.main.rise-ck8s.com/des-public/tutorials:${{ inputs.image_tag }} harbor.main.rise-ck8s.com/des-public/tutorials:latest
          docker push harbor.main.rise-ck8s.com/des-public/tutorials:latest
