name: Publish Docker Image

on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string
      docker_username:
        required: true
        type: string
      docker_password:
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Docker registry
        run: |
          echo "${{ inputs.docker_password }}" | docker login harbor.main.rise-ck8s.com -u "${{ inputs.docker_username }}" --password-stdin

      - name: Tag Docker image as "latest" and push
        run: |
          docker tag harbor.main.rise-ck8s.com/des-public/tutorials:${{ inputs.image_tag }} harbor.main.rise-ck8s.com/des-public/tutorials:latest
          docker push harbor.main.rise-ck8s.com/des-public/tutorials:latest
