name: Test Notebooks

on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Print image tag
        run: |
          echo "Candidate Image Tag: ${{ github.sha }}"

      - name: Print image tag before test
        run: |
          echo "Image Tag: ${{ inputs.image_tag }}"

      
      - name: Log in to Docker registry
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login harbor.main.rise-ck8s.com -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull Docker image
        run: |
          docker pull harbor.main.rise-ck8s.com/des-public/tutorials:${{ inputs.image_tag }}

      - name: Run notebook tests
        run: |
          chmod +x ./start_tests.sh
          DES_DOCKER_IMAGE="harbor.main.rise-ck8s.com/des-public/tutorials:${{ inputs.image_tag }}" ./start_tests.sh
