name: Test Notebooks

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    concurrency:
      group: test-notebooks-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker registry
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login harbor.main.rise-ck8s.com -u "$DOCKER_USER" --password-stdin

      - name: Pull Docker image for testing
        run: |
          docker pull harbor.main.rise-ck8s.com/des-public/tutorials:${{ needs.build.outputs.image_tag }}

      - name: Run notebook tests using start_tests.sh
        env:
          DES_DOCKER_IMAGE: harbor.main.rise-ck8s.com/des-public/tutorials:${{ needs.build.outputs.image_tag }}
        run: |
          chmod +x ./start_tests.sh
          ./start_tests.sh
