name: Test Notebooks

on:
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: Log in to Docker registry
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login harbor.main.rise-ck8s.com -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Set image_tag based on available image
        run: |
            if docker pull harbor.main.rise-ck8s.com/des-public/tutorials:${{ github.sha }}; then
              echo "image_tag=${{ github.sha }}" >> $GITHUB_ENV
            else
              docker pull harbor.main.rise-ck8s.com/des-public/tutorials:latest
              echo "image_tag=latest" >> $GITHUB_ENV
            fi
      - name: Run notebook tests
        run: |
          chmod +x ./start_tests.sh
          DES_DOCKER_IMAGE="harbor.main.rise-ck8s.com/des-public/tutorials:${{ env.image_tag }}" ./start_tests.sh
